src/config/__init__.py
import os


class FlaskConfig:
    ENVIRONMENT: str = os.getenv("ENVIRONMENT", "DEV")
    SECRET_KEY: str = os.getenv("SECRET_KEY", "s3cr3t_key")


class Database:
    _database: str = os.getenv("DB", "postgresql")
    _db_driver: str = os.getenv("DB_DRIVER", "psycopg2")
    _db_host: str = os.getenv("DB_HOST", "127.0.0.1")
    _db_port: int = os.getenv("DB_PORT", 5432)
    _db_username: str = os.getenv("DB_USER", "postgres")
    _db_password: str = os.getenv("DB_PASSWORD", "letsplay")
    _db_name: str = os.getenv("DB_NAME", "choraiinfo")


class SQLAlchemyConfig:
    track_modifications: bool = False
    database_uri: str = f"{Database._database}+{Database._db_driver}://{Database._db_username}:{Database._db_password}@{Database._db_host}:{Database._db_port}/{Database._db_name}"
    echo: bool = False
    native_unicode: str = "utf-8"
    commit_on_teardown: bool = False


class Configuration:
    ENV: str = FlaskConfig.ENVIRONMENT
    DEBUG: bool = FlaskConfig.ENVIRONMENT == "DEV"
    SECRET_KEY: str = FlaskConfig.SECRET_KEY
    SQLALCHEMY_DATABASE_URI: str = SQLAlchemyConfig.database_uri
    SQLALCHEMY_TRACK_MODIFICATIONS: bool = SQLAlchemyConfig.track_modifications
    SQLALCHEMY_ECHO: bool = SQLAlchemyConfig.echo
    SQLALCHEMY_COMMIT_ON_TEARDOWN: bool = SQLAlchemyConfig.commit_on_teardown
    SQLALCHEMY_NATIVE_UNICODE: str = SQLAlchemyConfig.native_unicode

src/controller/__init__.py
from flask_admin import Admin

from src.controller.blueprints.lost_item import lostitem_blueprint
from src.controller.blueprints.user import user_blueprint
from src.setup import app, db
from flask_admin.contrib.sqla import ModelView

from src.model import User, Vehicle, Laptop, CellPhone, SearchHistory

app.config['FLASK_ADMIN_SWATCH'] = 'cerulean'

admin = Admin(app, name='choraiinfo', template_mode='bootstrap3')

admin.add_view(ModelView(User, db.session))
admin.add_view(ModelView(Vehicle, db.session))
admin.add_view(ModelView(Laptop, db.session))
admin.add_view(ModelView(CellPhone, db.session))
admin.add_view(ModelView(SearchHistory, db.session))

app.register_blueprint(user_blueprint, url_prefix="/user")
app.register_blueprint(lostitem_blueprint, url_prefix="/item")

src/controller/blueprints/lost_item/__init__.py
from .routes import lostitem_blueprint

src/controller/blueprints/lost_item/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user

from .lost_item_crud import *

lostitem_blueprint = Blueprint("lostitembp", __name__, static_folder="../../../static",
                               template_folder="../../../templates")


@lostitem_blueprint.route("/select")
def select_item():
    return render_template("select_item.html")


@lostitem_blueprint.route("/report/vehicle", methods=["GET", "POST"])
@login_required
def report_vehicle():
    if request.method == "GET":
        return render_template("add_vehicle.html")
    if request.method == "POST":
        print(request.form)
        license = request.form.get("license")
        serial = request.form.get("serial")
        engine = request.form.get("engine")
        remarks = request.form.get("remarks")
        stolen = request.form.get("stolen") == "1"
        print(stolen)

        add_item(current_user.uid, ItemTypeEnum.VEHICLE, serial_number=serial, engine_number=engine,
                 license_number=license, remarks=remarks, is_stolen=stolen)
        return redirect(url_for("userbp.dashboard"))


@lostitem_blueprint.route("/report/laptop", methods=["GET", "POST"])
@login_required
def report_laptop():
    if request.method == "GET":
        return render_template("add_laptop.html")
    if request.method == "POST":
        serial = request.form.get("serial")
        macid = request.form.get("macid")
        gdno = request.form.get("gdno")
        stolen = request.form.get("stolen") == "1"

        add_item(current_user.uid, ItemTypeEnum.LAPTOP, serial_number=serial, mac_address=macid, gd_copy_number=gdno,
                 is_stolen=stolen)
        return redirect(url_for("userbp.dashboard"))


@lostitem_blueprint.route("/report/mobile", methods=["GET", "POST"])
@login_required
def report_mobile():
    if request.method == "GET":
        return render_template("add_mobile.html")
    if request.method == "POST":
        imei_1 = request.form.get("imei_1")
        imei_2 = request.form.get("imei_2")
        model = request.form.get("model")
        gdno = request.form.get("gdno")
        stolen = request.form.get("stolen") == "1"

        add_item(current_user.uid, ItemTypeEnum.CELL_PHONE, imei_1=imei_1, imei_2=imei_2, gd_copy_number=gdno,
                 is_stolen=stolen)
        return redirect(url_for("userbp.dashboard"))


@lostitem_blueprint.route("/search/vehicle", methods=["GET", "POST"])
def search_vehicle():
    if request.method == "GET":
        return render_template("search_vehicle.html")
    if request.method == "POST":
        string = request.form.get("string")
        sh = add_search_history_vehicle(string)
        print(sh.json)
        return render_template("show_vehicle.html", items=sh.matched_items())


@lostitem_blueprint.route("/search/laptop", methods=["GET", "POST"])
def search_laptop():
    if request.method == "GET":
        return render_template("search_laptop.html")
    if request.method == "POST":
        string = request.form.get("string")
        sh = add_search_history_laptop(string)
        print(sh.json)
        return render_template("show_laptop.html", items=sh.matched_items())


@lostitem_blueprint.route("/search/phone", methods=["GET", "POST"])
def search_phone():
    if request.method == "GET":
        return render_template("search_mobile.html")
    if request.method == "POST":
        string = request.form.get("string")
        sh = add_search_history_phone(string)
        print(sh.json)
        return render_template("show_mobile.html", items=sh.matched_items())

src/controller/blueprints/user/__init__.py
from .routes import user_blueprint

src/controller/blueprints/user/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import login_user, current_user, logout_user, login_required

from src.setup import login_manager
from .user_crud import *

user_blueprint = Blueprint("userbp", __name__, static_folder="../../../static", template_folder="../../../templates")


@login_manager.unauthorized_handler
def unauth_handler():
    return redirect(url_for("userbp.user_login"))


@user_blueprint.route("/register", methods=["GET", "POST"])
def user_register():
    if request.method == "GET":
        return render_template("register.html")
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        username = request.form.get("username")
        user, err = create_new_user(username, email, password)
        if err:
            flash(user)
            return redirect(url_for("userbp.user_register"))

        login_user(user)
        return redirect(url_for("userbp.dashboard"))


@user_blueprint.route("/login", methods=["GET", "POST"])
def user_login():
    if request.method == "GET":
        if current_user.is_authenticated:
            return redirect(url_for("userbp.dashboard"))
        return render_template("login.html")
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        if not user_check_credential(email, password):
            print("invalid")
            flash("Invalid credentials!")
            return redirect(url_for("userbp.user_login"))

        user = get_user_from_email(email)
        login_user(user)
        print(user.json)
        return redirect(url_for("userbp.dashboard"))


@user_blueprint.route("/logout")
def user_logout():
    if current_user.is_authenticated:
        logout_user()
    return redirect(url_for("home"))


@user_blueprint.route("/dashboard")
@login_required
def dashboard():
    return render_template("user_dash.html", user=current_user)

src/model/__init__.py
from .user import User, UserLevelEnum
from .lost_item import ItemTypeEnum, LostItem, Laptop, CellPhone, Vehicle
from .history import SearchHistory

src/setup/__init__.py
from .sqlalchemy import app, db
from .flask_app import login_manager

src/utilities/__init__.py
from .generator import Generator

src/templates/add_mobile.html
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> চুরি যাওয়া সকল জিনিষের সন্ধানে </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans" rel="stylesheet">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/main4.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/media.css') }}">


</head>

<body>

<nav class="navbar sticky-top navbar-toggleable-md navbar-dark bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('home') }}">Chorai Info</a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Made By:
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="https://github.com/tahmid-choyon">Md. Tahmid Hossain (14101148)</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="">Proudly Bangladeshi ♥
                    <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item nav-right navbar-right">
                <a class="nav-link" href="{{ url_for("userbp.user_logout") }}">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<div class="container">


    <div class="search">
        <div class="upper text-center">
            <h3>Hey {{ user }}</h3>
            </br>
            <h2>Register your stolen mobile</h2>
            <p>all fields are not mandatory</p>
        </div>
        <div class="lower text-right">
            <form action="{{ url_for("lostitembp.report_mobile") }}" method="POST">
                <div class="form-group">

                    <input type="text" class="form-control" name="imei_1" placeholder="IMEI 1" required>
                </div>
                <div class="form-group">

                    <input type="text" class="form-control" name="imei_2" placeholder="IMEI 2">
                </div>
                <div class="form-group">
                    <input type="text" class="form-control" name="gdno" placeholder="GD Copy No">
                </div>
                <div class="form-group">
                    <select name="stolen">
                        <option value="1">I lost it</option>
                        <option value="0">I have it</option>
                    </select>
                </div>

                <button type="submit" value="submit" class="button "><img
                        src="{{ url_for('static', filename='images/cursor.png') }}">
                </button>
            </form>
        </div>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>


<script src="{{ url_for('static', filename='js/main.js') }}"></script>

<script>
    window.jQuery || document.write('<script src="js/vendor/jquery-1.12.4.min.js"><\/script>')


</script>

<!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
<script>
    window.ga = function () {
        ga.q.push(arguments)
    };
    ga.q = [];
    ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto');
    ga('send', 'pageview')


</script>

<script>
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>
</body>

</html>

src/templates/user_dash.html
<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> চুরি যাওয়া সকল জিনিষের সন্ধানে </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
          integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
            integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
            crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/userdash.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/media.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Lato|Open+Sans" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.1.1.min.js" defer></script>
    <script src="dist/js/bootstrap-checkbox.min.js" defer></script>

</head>

<body>
<div class="container-fluid">

    <nav class="navbar sticky-top navbar-toggleable-md navbar-dark bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{{ url_for('home') }}">Chorai Info</a>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Made By:
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="https://github.com/tahmid-choyon">Md. Tahmid Hossain
                            (14101148)</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="">Proudly Bangladeshi ♥
                        <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item nav-right navbar-right">
                    <a class="nav-link" href="{{ url_for("userbp.user_logout") }}">Logout</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="upper text-center">
            <h2>Things You Own</h2>
            <p>Objects that you own are here, even if they are not lost yet.</p>
        </div>
        {% for m in user.cell_phones %}
            <!-- Device 1 Listed Here Underneath -->

            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#m{{ m.lost_item_id }}">
                Mobile
                ID: {{ m.imei_1 }}
            </button>

            <!--Data of Device 1 Here inside the Modal Box-->

            <div class="modal fade" id="m{{ m.lost_item_id }}" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">ID: {{ m.id }}</h4>
                        </div>
                        <div class="modal-body">
                            <li class="list-group-item">Object: Mobile Phone</li>
                            <li class="list-group-item">Device IMEI 1: {{ m.imei_1 }}</li>
                            <li class="list-group-item">Device IMEI 2: {{ m.imei_2 }}</li>
                            <li class="list-group-item"><p>Device Status : {% if m.is_stolen is sameas true %}
                                Stolen {% elif m.is_stolen is sameas false %} Not Stolen {% endif %}</p>
                            </li>
                            <li class="list-group-item">GD Number: {{ m.gd_copy_number }}</li>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
        {% for l in user.laptops %}
            <!-- Device 1 Listed Here Underneath -->

            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#l{{ l.lost_item_id }}">
                Laptop
                ID: {{ l.serial_number }} {{ l.mac_address }}
            </button>

            <!--Data of Device 1 Here inside the Modal Box-->

            <div class="modal fade" id="l{{ l.id }}" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">ID: {{ l.id }}</h4>
                        </div>
                        <div class="modal-body">
                            <li class="list-group-item">Object: Laptop</li>
                            <li class="list-group-item">Serial Number: {{ l.serial_number }}</li>
                            <li class="list-group-item">MacID: {{ l.mac_address }}</li>
                            <li class="list-group-item"><p>Device Status : {% if l.is_stolen is sameas true %}
                                Stolen {% elif l.is_stolen is sameas false %} Not Stolen {% endif %}</p>
                            </li>
                            <li class="list-group-item">GD Number: {{ l.gd_copy_number }}</li>

                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
        {% for v in user.vehicles %}
            <!-- Device 1 Listed Here Underneath -->

            <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#v{{ v.lost_item_id }}">
                Vehicle
                ID: {{ v.id }} {{ v.remarks }}
            </button>

            <!--Data of Device 1 Here inside the Modal Box-->

            <div class="modal fade" id="v{{ v.id }}" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">ID: {{ v.id }}</h4>
                        </div>
                        <div class="modal-body">
                            <li class="list-group-item">Object: Vehicle</li>
                            <li class="list-group-item">Model: {{ v.remarks }}</li>
                            <li class="list-group-item">Serial Number: {{ v.serial_number }}</li>
                            <li class="list-group-item">Engine Number: {{ v.engine_number }}</li>
                            <li class="list-group-item">License Number: {{ v.license_number }}</li>
                            <li class="list-group-item"><p>Device Status : {% if v.is_stolen is sameas true %}
                                Stolen {% elif v.is_stolen is sameas false %} Not Stolen {% endif %}</p>
                            </li>
                            <li class="list-group-item">GD Number: {{ v.gd_copy_number }}</li>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>
    <div class="container">
        <div class="upper text-center">
            <h2>Add Your Personal Devices</h2>
            <p>Add the Objects that you own here - you can change their status if you lose them later</p>
        </div>

        <div class="icons">
            <div class="row">
                <div class="col-sm-7 col-md-7 col-lg-7"></div>
            </div>
            <div class="row">
                <div class="col-xs-1 col-sm-1 col-md-3 col-lg-3"></div>
                {#<div class="col-xs-1 col-sm-4 col-md-1 col-lg-1 ">
                    <div class="icon">
                        <a href="#"><img class="img-responsive"
                                         src="{{ url_for('static', filename='images/bicycle.png') }}" alt="Bicycle"></a>
                    </div>
                </div>#}
                <div class="col-xs-1 col-sm-4 col-md-1 col-lg-1 ">
                    <div class="icon">
                        <a href="{{ url_for('lostitembp.report_vehicle') }}"><img class="img-responsive"
                                                                                  src="{{ url_for('static', filename='images/car.png') }}"
                                                                                  alt="Car"></a>
                    </div>
                </div>
                <div class="col-xs-1 col-sm-4 col-md-1 col-lg-1 ">
                    <div class="icon">
                        <a href="{{ url_for('lostitembp.report_mobile') }}"><img class="img-responsive"
                                                                                 src="{{ url_for('static', filename='images/LAPV2.png') }}"
                                                                                 alt="Mobile"></a>
                    </div>
                </div>
                <div class="col-xs-1 col-sm-4 col-md-1 col-lg-1 ">
                    <div class="icon">
                        <a href="{{ url_for('lostitembp.report_laptop') }}"><img class="img-responsive"
                                                                                 src="{{ url_for('static', filename='images/lap.png') }}"
                                                                                 alt="Laptop"></a>
                    </div>
                </div>
                <div class="col-xs-1 col-sm-4 col-md-1 col-lg-1">
                    <div class="icon">
                        <a href="{{ url_for('lostitembp.report_vehicle') }}"><img
                                src="{{ url_for('static', filename='images/bike.png') }}" alt="Motorcycle"></a>
                    </div>
                </div>
            </div>

        </div>


    </div>


</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"
        integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>


<script src="{{ url_for('static', filename='js/main.js') }}"></script>

<script>
    window.jQuery || document.write('<script src="js/vendor/jquery-1.12.4.min.js"><\/script>')

</script>

<!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
<script>
    window.ga = function () {
        ga.q.push(arguments)
    };
    ga.q = [];
    ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto');
    ga('send', 'pageview')

</script>

<script>
</script>
<script src="https://www.google-analytics.com/analytics.js" async defer></script>
</body>

</html>